import os
from dotenv import load_dotenv

load_dotenv()

SILENCE_THRESHOLD = 500
SILENCE_DURATION_MS = 1200
MAX_DURATION_S = 8
MIN_RECORDING_S = 1.5
FOLLOW_UP_MIN_RECORDING_S = float(os.getenv("FOLLOW_UP_MIN_RECORDING_S", "3.0"))
FOLLOW_UP_SILENCE_COUNT = int(os.getenv("FOLLOW_UP_SILENCE_COUNT", "2"))
FOLLOW_UP_TIMEOUT_S = float(os.getenv("FOLLOW_UP_TIMEOUT_S", "10"))
ACK_TEXT = os.getenv("ACK_TEXT", "Mm-hmm?")
SAMPLE_RATE = 16000
CHUNK = 1024
